//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinApp.LangResource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinApp.LangResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verification key.
        /// </summary>
        public static string Login_KeyEntry_PH {
            get {
                return ResourceManager.GetString("Login_KeyEntry_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login_LoginPutton_T {
            get {
                return ResourceManager.GetString("Login_LoginPutton_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bank&apos;s name.
        /// </summary>
        public static string Login_NameEntry_PH {
            get {
                return ResourceManager.GetString("Login_NameEntry_PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registry.
        /// </summary>
        public static string Login_RegLabel_T {
            get {
                return ResourceManager.GetString("Login_RegLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на From.
        /// </summary>
        public static string Registry_fromLable_T {
            get {
                return ResourceManager.GetString("Registry_fromLable_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Verification key.
        /// </summary>
        public static string Registry_KeyLabel_T {
            get {
                return ResourceManager.GetString("Registry_KeyLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Latitude.
        /// </summary>
        public static string Registry_LatitLabel_T {
            get {
                return ResourceManager.GetString("Registry_LatitLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        public static string Registry_LocationLabel_T {
            get {
                return ResourceManager.GetString("Registry_LocationLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Longitude.
        /// </summary>
        public static string Registry_LongLabel_T {
            get {
                return ResourceManager.GetString("Registry_LongLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        public static string Registry_MainLabel_T {
            get {
                return ResourceManager.GetString("Registry_MainLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bank&apos;s name.
        /// </summary>
        public static string Registry_NameLabel_T {
            get {
                return ResourceManager.GetString("Registry_NameLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registry.
        /// </summary>
        public static string Registry_RegButton_T {
            get {
                return ResourceManager.GetString("Registry_RegButton_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registry new Bank.
        /// </summary>
        public static string Registry_RegistryLabel_T {
            get {
                return ResourceManager.GetString("Registry_RegistryLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To.
        /// </summary>
        public static string Registry_toLabel_T {
            get {
                return ResourceManager.GetString("Registry_toLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WebSite.
        /// </summary>
        public static string Registry_WebLabel_T {
            get {
                return ResourceManager.GetString("Registry_WebLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Working time.
        /// </summary>
        public static string Registry_workLabel_T {
            get {
                return ResourceManager.GetString("Registry_workLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accuracy.
        /// </summary>
        public static string Settings_AccuracyLabel_T {
            get {
                return ResourceManager.GetString("Settings_AccuracyLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App.
        /// </summary>
        public static string Settings_AppLabel_T {
            get {
                return ResourceManager.GetString("Settings_AppLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font.
        /// </summary>
        public static string Settings_FontLabel_T {
            get {
                return ResourceManager.GetString("Settings_FontLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interface.
        /// </summary>
        public static string Settings_IntfLable_T {
            get {
                return ResourceManager.GetString("Settings_IntfLable_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language.
        /// </summary>
        public static string Settings_LangLabel_T {
            get {
                return ResourceManager.GetString("Settings_LangLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings_SettLabel_T {
            get {
                return ResourceManager.GetString("Settings_SettLabel_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Theme.
        /// </summary>
        public static string Settings_ThemeLabel_T {
            get {
                return ResourceManager.GetString("Settings_ThemeLabel_T", resourceCulture);
            }
        }
    }
}
